Some missing contracts and fixes to readme
marsfoundation/sparklend-advanced pull request #20
Opened 2024-04-01 04:33 UTC by hexonaut

Readme was incorrect with capped oracle and missing the new Lido + Rocket pool oracles.

2024-04-01 21:31 UTC, lucas-manuel approved these changes

2024-04-01 21:31 UTC, lucas-manuel commented on README.md
> +[WSTETHExchangeRateOracle](https://github.com/marsfoundation/sparklend-advanced/blob/master/src/WSTETHExchangeRateOracle.sol): Provides wstETH / USD by multiplying the wstETH exchange rate by ETH / U
wstETH/USD

2024-04-01 21:31 UTC, lucas-manuel commented on README.md
> +[WSTETHExchangeRateOracle](https://github.com/marsfoundation/sparklend-advanced/blob/master/src/WSTETHExchangeRateOracle.sol): Provides wstETH / USD by multiplying the wstETH exchange rate by ETH / U
ETH/USD

2024-04-01 21:31 UTC, lucas-manuel commented on README.md
> +[RETHExchangeRateOracle](https://github.com/marsfoundation/sparklend-advanced/blob/master/src/RETHExchangeRateOracle.sol): Provides rETH / USD by multiplying the rETH exchange rate by ETH / USD. Used
rETH/USD, ETH/USD

2024-04-01 21:31 UTC, lucas-manuel requested changes
Comments above

2024-04-02 07:17 UTC, hexonaut commented on README.md
> +[WSTETHExchangeRateOracle](https://github.com/marsfoundation/sparklend-advanced/blob/master/src/WSTETHExchangeRateOracle.sol): Provides wstETH / USD by multiplying the wstETH exchange rate by ETH / U
fixed

2024-04-02 07:17 UTC, hexonaut commented on README.md
> +[RETHExchangeRateOracle](https://github.com/marsfoundation/sparklend-advanced/blob/master/src/RETHExchangeRateOracle.sol): Provides rETH / USD by multiplying the rETH exchange rate by ETH / USD. Used
fixed

2024-04-02 15:37 UTC, lucas-manuel approved these changes

2024-04-02 15:54 UTC, merged