[SC-229] Added capped oracle
marsfoundation/sparklend-advanced pull request #3
Opened 2023-11-08 13:38 UTC by hexonaut

Adding a capped oracle which has a maximum value.

2023-11-09 16:01 UTC, lucas-manuel requested changes

2023-11-09 16:01 UTC, lucas-manuel commented on test/CappedOracle.t.sol
> +    }
```suggestion
        assertEq(oracle.latestAnswer(), 0.8e8);
        assertEq(oracle.decimals(),     8);
```

2023-11-09 16:01 UTC, lucas-manuel commented on test/CappedOracle.t.sol
> +    }
Lets add one more prixe_below_max with `1e8 - 1`

2023-11-09 16:01 UTC, lucas-manuel requested changes
Small changes then lgtm

2023-11-09 16:01 UTC, lucas-manuel requested changes
Small changes then lgtm

2023-11-10 11:20 UTC, hexonaut commented on test/CappedOracle.t.sol
> +    }
done

2023-11-10 11:21 UTC, hexonaut commented on test/CappedOracle.t.sol
> +    }
added

2023-11-10 12:47 UTC, barrutko reviewed
Two minor comments, other than that LGTM.

2023-11-10 12:47 UTC, barrutko commented on test/CappedOracle.t.sol
> +        assertEq(oracle.decimals(),     8);
I'd check the `source` address as well.

2023-11-10 12:47 UTC, barrutko commented on test/CappedOracle.t.sol
> +        assertEq(oracle.decimals(),     8);
Plus, not sure if that's necessary, but the test could also cover the revert on `_maxPrice <= 0`

2023-11-10 13:16 UTC, hexonaut commented on test/CappedOracle.t.sol
> +        assertEq(oracle.decimals(),     8);
oops yes good catch both of these should be tested. fixed

2023-11-10 13:30 UTC, barrutko approved these changes

2023-11-10 16:48 UTC, lucas-manuel approved these changes

2023-11-10 16:48 UTC, lucas-manuel approved these changes

2023-11-11 07:29 UTC, merged