Improve test coverage
marsfoundation/sparklend-advanced pull request #4
Opened 2023-11-08 15:00 UTC by hexonaut

Improving the test coverage on the IRMs by comparing it to the default version. Ignoring stable rate borrow as we don't use it.

2023-11-13 20:55 UTC, lucas-manuel requested changes

2023-11-13 20:55 UTC, lucas-manuel commented on test/InterestRateStrategyBase.t.sol
> +        params.aToken            = makeAddr("aToken");
```suggestion
        liquidityAvailable       = bound(liquidityAvailable,    0, MAX_TOKEN_AMOUNT);
        params.unbacked          = bound(params.unbacked,       0, MAX_TOKEN_AMOUNT);
        params.liquidityAdded    = bound(params.liquidityAdded, 0, MAX_TOKEN_AMOUNT);
        params.liquidityTaken    = bound(params.liquidityTaken, 0, liquidityAvailable + params.liquidityAdded);
        params.totalStableDebt   = 0;
        params.totalVariableDebt = bound(params.totalVariableDebt, 0, MAX_TOKEN_AMOUNT);
        params.reserveFactor     = bound(params.reserveFactor,     0, 100_00);
        params.reserve           = address(asset);
        params.aToken            = makeAddr("aToken");
```

2023-11-13 20:55 UTC, lucas-manuel commented on test/InterestRateStrategyBase.t.sol
> +        assertEq(expectedVariableBorrowRate, actualVariableBorrowRate, "variable borrow rate mismatch");
```suggestion
        assertEq(expectedLiquidityRate,      actualLiquidityRate,      "liquidity rate mismatch");
        assertEq(expectedVariableBorrowRate, actualVariableBorrowRate, "variable borrow rate mismatch");
```

2023-11-13 20:55 UTC, lucas-manuel requested changes
Nitpicks then good to merge

2023-11-13 20:55 UTC, lucas-manuel requested changes
Nitpicks then good to merge

2023-11-13 20:59 UTC, lucas-manuel commented
Also made a ticket here: https://linear.app/phoenixlabs/issue/SC-241/add-full-test-coverage-for-strategies-in-sparklend-advanced

Think this is a great start to improve test coverage, but want to add dedicated tests for calculateInterestRates as well.

Could also discuss removing stable logic altogether for these contracts.

2023-11-14 06:43 UTC, hexonaut commented on test/InterestRateStrategyBase.t.sol
> +        params.aToken            = makeAddr("aToken");
done

2023-11-14 06:44 UTC, hexonaut commented on test/InterestRateStrategyBase.t.sol
> +        assertEq(expectedVariableBorrowRate, actualVariableBorrowRate, "variable borrow rate mismatch");
done

2023-11-14 06:44 UTC, hexonaut commented
Ya agree about removing the stable borrow logic. It's wasting gas at the very least.

2023-11-14 15:06 UTC, lucas-manuel approved these changes

2023-11-20 16:10 UTC, barrutko approved these changes

2023-11-21 13:56 UTC, merged