[SC-241] Refactor Base/Kink Rate Target IRMs
marsfoundation/sparklend-advanced pull request #8
Opened 2023-12-07 13:15 UTC by hexonaut

To reduce code duplication these IRMs will inherit from the custom variable rate IRM which removes stable borrow logic.

2023-12-07 15:34 UTC, hexonaut commented
Coverage seems broken...?

2023-12-12 17:38 UTC, barrutko approved these changes
✅ In `RateTargetBaseInterestRateStrategy` the behaviour of `getBaseVariableBorrowRate()` is correct
✅ In `RateTargetKinkInterestRateStrategy` the behaviour of `getVariableRateSlope1()` is correct
✅ `VariableBorrowInterestRateStrategy` refactoring makes sense
✅ I didn't find any style-related issues, assuming that we keep Aave style on purpose in some places

IMO this is good to be merged

2023-12-14 10:10 UTC, lucas-manuel requested changes
Small changes then LGTM, ran fuzz tests with 100k runs and got the same issue with the rounding and that fix fixes it so lgtm after this.

2023-12-14 10:10 UTC, lucas-manuel commented on src/RateTargetBaseInterestRateStrategy.sol
```suggestion
import { IRateSource } from './interfaces/IRateSource.sol';
```

2023-12-14 10:10 UTC, lucas-manuel commented on src/RateTargetKinkInterestRateStrategy.sol
```suggestion
import { IRateSource } from './interfaces/IRateSource.sol';
```

2023-12-14 10:10 UTC, lucas-manuel commented on src/RateTargetKinkInterestRateStrategy.sol
> +     *                                 Note: this discounts the base variable borrow rate
This

2023-12-14 10:10 UTC, lucas-manuel commented on src/RateTargetBaseInterestRateStrategy.sol
> +     * @param provider                     The address of the PoolAddressesProvider contract
Periods at end of all natspec

2023-12-14 10:10 UTC, lucas-manuel commented on src/VariableBorrowInterestRateStrategy.sol
>      // Base variable borrow rate when usage rate = 0. Expressed in ray
Expressed in ray.

2023-12-14 11:36 UTC, hexonaut commented on src/RateTargetBaseInterestRateStrategy.sol
fixed

2023-12-14 11:36 UTC, hexonaut commented on src/RateTargetKinkInterestRateStrategy.sol
fixed

2023-12-14 11:36 UTC, hexonaut commented on src/RateTargetKinkInterestRateStrategy.sol
> +     *                                 Note: this discounts the base variable borrow rate
fixed

2023-12-14 11:37 UTC, hexonaut commented on src/RateTargetBaseInterestRateStrategy.sol
> +     * @param provider                     The address of the PoolAddressesProvider contract
fixed

2023-12-14 11:37 UTC, hexonaut commented on src/VariableBorrowInterestRateStrategy.sol
>      // Base variable borrow rate when usage rate = 0. Expressed in ray
fixed

2023-12-14 12:21 UTC, barrutko approved these changes

2023-12-14 12:22 UTC, lucas-manuel approved these changes

2023-12-14 12:29 UTC, merged